package dev.nandobez.macc.codegen;

import java.lang.reflect.*;

/** Converts a Java record (@Model) into a TypeScript interface. */
public class ModelEmitter {

    public String emit(Class<?> rec) {
        if (!rec.isRecord())
            return "// " + rec.getSimpleName() + " is not a record — only records are supported\n";

        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Macc — do not edit by hand.\n");
        sb.append("export interface ").append(rec.getSimpleName()).append(" {\n");
        for (RecordComponent c : rec.getRecordComponents()) {
            sb.append("  ").append(c.getName()).append(": ").append(tsType(c.getType(), c.getGenericType())).append(";\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private String tsType(Class<?> raw, Type generic) {
        if (raw == String.class)  return "string";
        if (raw == Boolean.class || raw == boolean.class) return "boolean";
        if (raw == Integer.class || raw == int.class || raw == Long.class || raw == long.class
            || raw == Double.class || raw == double.class || raw == Float.class || raw == float.class)
            return "number";
        if (raw.isArray()) return tsType(raw.getComponentType(), null) + "[]";
        if (java.util.List.class.isAssignableFrom(raw) && generic instanceof ParameterizedType pt) {
            Type t = pt.getActualTypeArguments()[0];
            if (t instanceof Class<?> c) return c.getSimpleName() + "[]";
        }
        if (java.time.Instant.class == raw || java.time.LocalDate.class == raw || java.time.LocalDateTime.class == raw)
            return "string";
        if (java.math.BigDecimal.class == raw) return "number";
        if (java.util.UUID.class == raw)       return "string";
        if (raw == Object.class)               return "any";
        return raw.getSimpleName();
    }
}
