package dev.nandobez.macc.codegen;

import dev.nandobez.macc.dsl.*;
import dev.nandobez.macc.dsl.annotations.*;

import java.lang.reflect.*;
import java.util.*;

/** Reflects a Component subclass + emits its .tsx file. */
public class PageEmitter {

    public static class Result {
        public final String name;
        public final String tsx;
        public final String routePath;
        public final Set<String> typeImports = new LinkedHashSet<>();
        public Result(String name, String tsx, String routePath) {
            this.name = name; this.tsx = tsx; this.routePath = routePath;
        }
    }

    public Result emit(Class<?> cls) throws Exception {
        String compName = cls.getSimpleName();
        Page page = cls.getAnnotation(Page.class);
        String routePath = page == null ? null : (page.path().isEmpty() ? page.value() : page.path());

        Object instance = cls.getDeclaredConstructor().newInstance();

        // Discover state / props / fetch / refs from declared fields.
        List<StateField> states = new ArrayList<>();
        List<FetchField> fetches = new ArrayList<>();
        List<PropField>  props   = new ArrayList<>();
        List<RefField>   refs    = new ArrayList<>();
        Set<String> imports = new LinkedHashSet<>();

        for (Field f : cls.getDeclaredFields()) {
            f.setAccessible(true);
            if (f.isAnnotationPresent(State.class)) {
                Object val = f.get(instance);
                states.add(new StateField(f.getName(), tsType(f, imports), tsLiteral(val)));
            } else if (f.isAnnotationPresent(Fetch.class)) {
                Fetch ff = f.getAnnotation(Fetch.class);
                String url = !ff.value().isEmpty() ? ff.value() : ff.url();
                String tsT = tsType(f, imports);
                fetches.add(new FetchField(f.getName(), tsT, url,
                    ff.empty(), ff.error(), ff.loading()));
            } else if (f.isAnnotationPresent(Prop.class)) {
                Object val = f.get(instance);
                props.add(new PropField(f.getName(), tsType(f, imports), tsLiteral(val)));
            } else if (f.isAnnotationPresent(Ref.class)) {
                Ref r = f.getAnnotation(Ref.class);
                refs.add(new RefField(f.getName(), r.value()));
            }
        }

        // Actions — emit TS handler functions for @Action-annotated methods.
        List<String> actions = new ArrayList<>();
        Set<String> actionImports = new LinkedHashSet<>();
        var actionEmitter = new ActionEmitter();
        for (Method m : cls.getDeclaredMethods()) {
            if (m.isAnnotationPresent(Action.class)) {
                var g = actionEmitter.emit(m);
                actions.add(g.functionSource());
                for (Parameter p : m.getParameters()) {
                    if (p.getType().isAnnotationPresent(Model.class)) {
                        imports.add("import type { " + p.getType().getSimpleName() + " } from \"../types/" + p.getType().getSimpleName() + "\";");
                    }
                }
            }
        }

        // Render the Element tree.
        Method renderMethod = cls.getDeclaredMethod("render");
        renderMethod.setAccessible(true);
        Element tree = (Element) renderMethod.invoke(instance);
        var emitter = new TsxEmitter();
        String body = emitter.emit(tree);
        for (var entry : emitter.externalImports.entrySet()) {
            imports.add("import { " + String.join(", ", entry.getValue()) + " } from \"" + entry.getKey() + "\";");
        }

        StringBuilder src = new StringBuilder();
        src.append("// Generated by Macc — do not edit by hand.\n");
        src.append("import { useState, useEffect } from \"react\";\n");
        if (containsClsx(body)) src.append("import { clsx } from \"clsx\";\n");
        for (String imp : imports) src.append(imp).append("\n");
        if (!fetches.isEmpty()) src.append("import { Spinner, ErrorBanner, EmptyState } from \"../components/StateViews\";\n");
        src.append("\n");

        // Props interface
        if (!props.isEmpty()) {
            src.append("interface ").append(compName).append("Props {\n");
            for (var p : props) {
                src.append("  ").append(p.name).append("?: ").append(p.tsType).append(";\n");
            }
            src.append("}\n\n");
        }

        // Emit action handlers at module scope (before component function).
        for (String a : actions) {
            src.append(a).append("\n");
        }

        String params = props.isEmpty() ? ""
            : "{ " + String.join(", ",
                props.stream().map(p -> p.defaultLiteral == null
                    ? p.name
                    : p.name + " = " + p.defaultLiteral).toList())
            + " }: " + compName + "Props";

        src.append("export default function ").append(compName).append("(").append(params).append(") {\n");

        for (var s : states) {
            src.append("  const [").append(s.name).append(", set").append(cap(s.name)).append("] = useState<").append(s.tsType).append(">(").append(s.defaultLiteral).append(");\n");
        }
        for (var f : fetches) {
            src.append("  const [").append(f.name).append(", set").append(cap(f.name)).append("] = useState<").append(f.tsType).append(">([] as any);\n");
            src.append("  const [").append(f.name).append("Loading, set").append(cap(f.name)).append("Loading] = useState(true);\n");
            src.append("  const [").append(f.name).append("Error, set").append(cap(f.name)).append("Error] = useState<string | null>(null);\n");
            src.append("  useEffect(() => {\n");
            src.append("    fetch(\"").append(f.url).append("\")\n");
            src.append("      .then(r => r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`)))\n");
            src.append("      .then(set").append(cap(f.name)).append(")\n");
            src.append("      .catch(e => set").append(cap(f.name)).append("Error(e.message))\n");
            src.append("      .finally(() => set").append(cap(f.name)).append("Loading(false));\n");
            src.append("  }, []);\n");
            src.append("  if (").append(f.name).append("Loading) return <Spinner />;\n");
            src.append("  if (").append(f.name).append("Error)   return <ErrorBanner error={").append(f.name).append("Error} />;\n");
            if (!f.empty.isEmpty())
                src.append("  if (Array.isArray(").append(f.name).append(") && ").append(f.name).append(".length === 0) return <EmptyState message=\"").append(f.empty).append("\" />;\n");
        }
        for (var r : refs) {
            src.append("  const ").append(r.name).append(" = useRef<").append(r.tsType).append(">(null);\n");
        }
        src.append("  return (\n");
        for (String line : body.split("\n")) src.append("    ").append(line).append("\n");
        src.append("  );\n");
        src.append("}\n");

        Result result = new Result(compName, src.toString(), routePath);
        return result;
    }

    // ---------- helpers ----------
    private record StateField(String name, String tsType, String defaultLiteral) {}
    private record FetchField(String name, String tsType, String url, String empty, String error, String loading) {}
    private record PropField(String name, String tsType, String defaultLiteral) {}
    private record RefField(String name, String tsType) {}

    private static String cap(String s) { return Character.toUpperCase(s.charAt(0)) + s.substring(1); }

    private static boolean containsClsx(String src) { return src.contains("clsx("); }

    private static String tsLiteral(Object v) {
        if (v == null) return "null";
        if (v instanceof String s) return "\"" + s.replace("\"", "\\\"") + "\"";
        if (v instanceof Boolean) return v.toString();
        if (v instanceof Number) return v.toString();
        if (v instanceof List<?> l && l.isEmpty()) return "[]";
        if (v instanceof Map<?, ?> m && m.isEmpty()) return "{}";
        if (v.getClass().isEnum()) return "\"" + ((Enum<?>) v).name() + "\"";
        return "null /* unsupported default */";
    }

    private static String tsType(Field f, Set<String> imports) {
        Class<?> raw = f.getType();
        if (raw == String.class) return "string";
        if (raw == Boolean.class || raw == boolean.class) return "boolean";
        if (raw == Integer.class || raw == int.class || raw == Long.class || raw == long.class
            || raw == Double.class || raw == double.class || raw == Float.class || raw == float.class)
            return "number";
        if (List.class.isAssignableFrom(raw)) {
            String inner = "any";
            if (f.getGenericType() instanceof ParameterizedType pt) {
                Type t = pt.getActualTypeArguments()[0];
                if (t instanceof Class<?> tc) {
                    inner = tc.getSimpleName();
                    if (tc.isAnnotationPresent(Model.class))
                        imports.add("import type { " + tc.getSimpleName() + " } from \"../types/" + tc.getSimpleName() + "\";");
                }
            }
            return inner + "[]";
        }
        if (Var.class.isAssignableFrom(raw)) {
            if (f.getGenericType() instanceof ParameterizedType pt) {
                Type t = pt.getActualTypeArguments()[0];
                if (t instanceof Class<?> tc) return tc.getSimpleName();
                if (t instanceof ParameterizedType inner) {
                    Type[] iargs = inner.getActualTypeArguments();
                    if (iargs.length == 1 && iargs[0] instanceof Class<?> ic) {
                        if (ic.isAnnotationPresent(Model.class))
                            imports.add("import type { " + ic.getSimpleName() + " } from \"../types/" + ic.getSimpleName() + "\";");
                        return ic.getSimpleName() + "[]";
                    }
                }
            }
            return "any";
        }
        if (raw.isAnnotationPresent(Model.class)) {
            imports.add("import type { " + raw.getSimpleName() + " } from \"../types/" + raw.getSimpleName() + "\";");
            return raw.getSimpleName();
        }
        return "any";
    }
}
