package dev.nandobez.macc.cmd;

import dev.nandobez.macc.codegen.*;
import picocli.CommandLine.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.Callable;

import static dev.nandobez.macc.cmd.Tui.*;

@Command(name = "codegen", description = "Scan @Page/@Model classes and emit .tsx + types.")
public class CodegenCmd implements Callable<Integer> {

    @Option(names = {"-d", "--dir"}, defaultValue = ".", description = "Project root.")
    Path projectRoot;

    @Option(names = "--frontend", defaultValue = "src/main/frontend", description = "Frontend output dir.")
    Path frontend;

    public Integer call() throws Exception {
        banner("macc codegen", projectRoot.toAbsolutePath().toString());

        var scan = ProjectScanner.scan(projectRoot);
        info("found " + scan.pages().size() + " page(s) and " + scan.models().size() + " model(s)");

        Path outRoot   = projectRoot.resolve(frontend);
        Path pagesDir  = outRoot.resolve("pages");
        Path typesDir  = outRoot.resolve("types");
        Path libDir    = outRoot.resolve("lib");
        Files.createDirectories(pagesDir);
        Files.createDirectories(typesDir);
        Files.createDirectories(libDir);

        // Emit models.
        var modelEmitter = new ModelEmitter();
        for (var m : scan.models()) {
            String tsx = modelEmitter.emit(m);
            Path p = typesDir.resolve(m.getSimpleName() + ".ts");
            Files.writeString(p, tsx);
            wrote(p.toString());
        }

        // Emit pages.
        var pageEmitter = new PageEmitter();
        List<PageEmitter.Result> pages = new ArrayList<>();
        for (var pg : scan.pages()) {
            try {
                var r = pageEmitter.emit(pg);
                pages.add(r);
                Path p = pagesDir.resolve(r.name + ".tsx");
                Files.writeString(p, r.tsx);
                wrote(p.toString());
            } catch (Throwable t) {
                error("failed to emit " + pg.getSimpleName() + ": " + t.getMessage());
                t.printStackTrace();
            }
        }

        // Emit routes.
        emitRoutes(outRoot.resolve("routes.tsx"), pages);
        emitStateViews(outRoot.resolve("components/StateViews.tsx"));

        return 0;
    }

    private void emitRoutes(Path file, List<PageEmitter.Result> pages) throws Exception {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Macc — do not edit by hand.\n");
        sb.append("import { lazy, Suspense } from \"react\";\n");
        sb.append("import { createBrowserRouter, RouterProvider } from \"react-router-dom\";\n");
        sb.append("import { Spinner } from \"./components/StateViews\";\n\n");
        for (var p : pages) {
            sb.append("const ").append(p.name).append(" = lazy(() => import(\"./pages/").append(p.name).append("\"));\n");
        }
        sb.append("\nconst withSuspense = (el: React.ReactNode) => (\n  <Suspense fallback={<Spinner />}>{el}</Suspense>\n);\n\n");
        sb.append("export const router = createBrowserRouter([\n");
        for (var p : pages) {
            if (p.routePath == null) continue;
            sb.append("  { path: \"").append(p.routePath).append("\", element: withSuspense(<").append(p.name).append(" />) },\n");
        }
        sb.append("]);\n\n");
        sb.append("export function AppRouter() { return <RouterProvider router={router} />; }\n");
        Files.writeString(file, sb.toString());
        wrote(file.toString());
    }

    private void emitStateViews(Path file) throws Exception {
        Files.createDirectories(file.getParent());
        String tsx = """
            // Generated by Macc — minimal state views; replace with your own.
            export function Spinner() { return <div className="p-4 text-sm text-gray-500">Loading…</div>; }
            export function ErrorBanner({ error }: { error: string }) {
              return <div className="p-4 rounded bg-red-50 text-red-700">{error}</div>;
            }
            export function EmptyState({ message }: { message: string }) {
              return <div className="p-8 text-center text-gray-400">{message}</div>;
            }
            """;
        Files.writeString(file, tsx);
        wrote(file.toString());
    }
}
